import { sql } from "drizzle-orm";
import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const organizations = sqliteTable("organizations", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  plan: text("plan", { enum: ["free", "team", "business", "enterprise"] }).notNull().default("free"),
  monthlyMinuteLimit: integer("monthly_minute_limit").notNull().default(120),
  retentionDays: integer("retention_days").notNull().default(30),
  automationMode: text("automation_mode", { enum: ["draft", "approval", "automatic"] }).notNull().default("approval"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const memberships = sqliteTable("memberships", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  email: text("email").notNull(),
  displayName: text("display_name").notNull(),
  role: text("role", { enum: ["admin", "supervisor", "seller"] }).notNull(),
  teamId: text("team_id"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("membership_org_email_idx").on(table.organizationId, table.email)]);

export const calls = sqliteTable("calls", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull().references(() => organizations.id),
  externalId: text("external_id"),
  customerName: text("customer_name").notNull().default("در انتظار استخراج"),
  companyName: text("company_name"),
  phoneNumber: text("phone_number"),
  city: text("city"),
  province: text("province"),
  sellerName: text("seller_name").notNull().default("در انتظار تشخیص"),
  sellerEmail: text("seller_email"),
  productName: text("product_name"),
  productCategory: text("product_category"),
  salesStage: text("sales_stage"),
  leadTemperature: text("lead_temperature"),
  originalFileName: text("original_file_name").notNull(),
  objectKey: text("object_key").notNull(),
  mimeType: text("mime_type").notNull(),
  sizeBytes: integer("size_bytes").notNull(),
  source: text("source", { enum: ["upload", "api", "telephony"] }).notNull().default("upload"),
  status: text("status").notNull().default("queued"),
  outcome: text("outcome", { enum: ["won", "lost", "follow_up", "unknown"] }).notNull().default("unknown"),
  outcomeConfirmed: integer("outcome_confirmed", { mode: "boolean" }).notNull().default(false),
  durationSeconds: real("duration_seconds"),
  direction: text("direction"),
  score: real("score"),
  sentiment: text("sentiment"),
  riskFlagsJson: text("risk_flags_json", { mode: "json" }).$type<string[]>(),
  followupRequired: integer("followup_required", { mode: "boolean" }).notNull().default(false),
  followupAt: text("followup_at"),
  hasManualCorrection: integer("has_manual_correction", { mode: "boolean" }).notNull().default(false),
  analysisVersion: text("analysis_version"),
  analysisJson: text("analysis_json", { mode: "json" }).$type<Record<string, unknown>>(),
  errorMessage: text("error_message"),
  errorType: text("error_type"),
  failedStage: text("failed_stage"),
  retryCount: integer("retry_count").notNull().default(0),
  lastRetryAt: text("last_retry_at"),
  nextRetryAt: text("next_retry_at"),
  worker: text("worker"),
  correlationId: text("correlation_id"),
  sourcePath: text("source_path"),
  fileHash: text("file_hash"),
  detectedAt: text("detected_at"),
  importedAt: text("imported_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("calls_org_external_idx").on(table.organizationId, table.externalId),
  index("idx_calls_org_created").on(table.organizationId, table.createdAt),
  index("idx_calls_org_status_created").on(table.organizationId, table.status, table.createdAt),
  index("idx_calls_org_seller_created").on(table.organizationId, table.sellerEmail, table.createdAt),
  index("idx_calls_org_followup").on(table.organizationId, table.followupRequired, table.followupAt),
]);

export const transcriptSegments = sqliteTable("transcript_segments", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull(),
  callId: text("call_id").notNull().references(() => calls.id, { onDelete: "cascade" }),
  position: integer("position").notNull(),
  speakerLabel: text("speaker_label").notNull(),
  speakerRole: text("speaker_role", { enum: ["agent", "seller", "customer", "unknown", "other"] }).notNull().default("unknown"),
  speakerRoleConfidence: real("speaker_role_confidence"),
  startSeconds: real("start_seconds"),
  endSeconds: real("end_seconds"),
  content: text("content").notNull(),
  normalizedText: text("normalized_text"),
  isManuallyCorrected: integer("is_manually_corrected", { mode: "boolean" }).notNull().default(false),
  correctionUserId: text("correction_user_id"),
  editedBy: text("edited_by"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("idx_segments_org_call_position").on(table.organizationId, table.callId, table.position)]);

export const tasks = sqliteTable("tasks", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull(),
  callId: text("call_id").references(() => calls.id, { onDelete: "set null" }),
  customerName: text("customer_name").notNull(),
  companyName: text("company_name"),
  title: text("title").notNull(),
  assigneeEmail: text("assignee_email"),
  priority: text("priority", { enum: ["low", "normal", "high", "critical"] }).notNull().default("normal"),
  status: text("status", { enum: ["open", "in_progress", "done", "cancelled"] }).notNull().default("open"),
  dueAt: text("due_at"),
  reason: text("reason"),
  completionNote: text("completion_note"),
  completedAt: text("completed_at"),
  creationMethod: text("creation_method").notNull().default("manual"),
  evidenceJson: text("evidence_json", { mode: "json" }).$type<Record<string, unknown>>(),
  aiSuggested: integer("ai_suggested", { mode: "boolean" }).notNull().default(false),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("idx_tasks_org_status_due").on(table.organizationId, table.status, table.dueAt)]);

export const processingEvents = sqliteTable("processing_events", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull(),
  callId: text("call_id").notNull().references(() => calls.id, { onDelete: "cascade" }),
  stage: text("stage").notNull(),
  status: text("status").notNull(),
  errorType: text("error_type"),
  safeMessage: text("safe_message"),
  stackTrace: text("stack_trace"),
  retryCount: integer("retry_count").notNull().default(0),
  worker: text("worker"),
  correlationId: text("correlation_id"),
  startedAt: text("started_at"),
  finishedAt: text("finished_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  index("idx_processing_org_status_created").on(table.organizationId, table.status, table.createdAt),
  index("idx_processing_org_call_created").on(table.organizationId, table.callId, table.createdAt),
]);

export const extractionEvidence = sqliteTable("extraction_evidence", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull(),
  callId: text("call_id").notNull().references(() => calls.id, { onDelete: "cascade" }),
  fieldName: text("field_name").notNull(),
  extractedValue: text("extracted_value"),
  confidence: real("confidence"),
  sourceSegmentIdsJson: text("source_segment_ids_json", { mode: "json" }).$type<string[]>(),
  exactQuote: text("exact_quote"),
  startSeconds: real("start_seconds"),
  endSeconds: real("end_seconds"),
  extractionMethod: text("extraction_method"),
  validationStatus: text("validation_status").notNull().default("unsupported"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("idx_evidence_org_call").on(table.organizationId, table.callId)]);

export const glossaryEntries = sqliteTable("glossary_entries", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull(),
  term: text("term").notNull(),
  normalizedTerm: text("normalized_term").notNull(),
  category: text("category").notNull(),
  aliasesJson: text("aliases_json", { mode: "json" }).$type<string[]>(),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [uniqueIndex("idx_glossary_org_normalized").on(table.organizationId, table.normalizedTerm, table.category)]);

export const issabelSettings = sqliteTable("issabel_settings", {
  organizationId: text("organization_id").primaryKey(),
  importMode: text("import_mode").notNull().default("disabled"),
  recordingsPath: text("recordings_path"),
  sftpHost: text("sftp_host"),
  sftpPort: integer("sftp_port").notNull().default(22),
  sftpUsername: text("sftp_username"),
  sftpRemotePath: text("sftp_remote_path"),
  pollInterval: integer("poll_interval").notNull().default(60),
  fileStabilitySeconds: integer("file_stability_seconds").notNull().default(15),
  allowedExtensions: text("allowed_extensions").notNull().default("wav,mp3,gsm"),
  quarantinePath: text("quarantine_path"),
  filenamePattern: text("filename_pattern"),
  enabled: integer("enabled", { mode: "boolean" }).notNull().default(false),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const messageDrafts = sqliteTable("message_drafts", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull(),
  callId: text("call_id").references(() => calls.id, { onDelete: "set null" }),
  channel: text("channel", { enum: ["sms", "whatsapp", "email"] }).notNull(),
  recipientMasked: text("recipient_masked"),
  subject: text("subject"),
  content: text("content").notNull(),
  status: text("status", { enum: ["draft", "pending_approval", "approved", "scheduled", "sent", "rejected", "failed"] }).notNull().default("pending_approval"),
  approvedBy: text("approved_by"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const integrations = sqliteTable("integrations", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull(),
  kind: text("kind", { enum: ["telephony", "crm", "webhook", "sms", "email", "whatsapp", "api"] }).notNull(),
  name: text("name").notNull(),
  status: text("status", { enum: ["active", "inactive", "error"] }).notNull().default("inactive"),
  encryptedConfig: text("encrypted_config"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const scorecardVersions = sqliteTable("scorecard_versions", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull(),
  version: integer("version").notNull(),
  name: text("name").notNull(),
  criteriaJson: text("criteria_json", { mode: "json" }).$type<Array<{ key: string; label: string; weight: number }>>().notNull(),
  active: integer("active", { mode: "boolean" }).notNull().default(false),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const auditLogs = sqliteTable("audit_logs", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull(),
  actorEmail: text("actor_email").notNull(),
  action: text("action").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id"),
  metadataJson: text("metadata_json", { mode: "json" }).$type<Record<string, unknown>>(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
